### ISSUE TITLE
[feat] : 테스트 코드를 작성하여 REST Docs를 적용한다

### ISSUE THREAD

**Issue by bbbang105** [onetime-with-members/backend#114]
### 📝 Description

- 테스트 코드를 작성하여 REST Docs를 적용한다

---

### 📝 Todo

- [x] EventController 테스트 코드 작성
- [ ] FixedController 테스트 코드 작성
- [ ] MemberController 테스트 코드 작성
- [ ] ScheduleController 테스트 코드 작성
- [ ] TokenController 테스트 코드 작성
- [ ] UrlController 테스트 코드 작성
- [ ] UserController 테스트 코드 작성
