### ISSUE TITLE
[style] : 주석을 추가하여 API 설명을 구체화한다

### ISSUE THREAD

**Issue by bbbang105** [onetime-with-members/backend#115]
### 📝 Description

- 주석을 추가하여 API 설명을 구체화한다

---

### 📝 Todo

- [ ] EventController 주석 추가
- [ ] FixedController 주석 추가
- [ ] MemberController 주석 추가
- [ ] ScheduleController 주석 추가
- [ ] TokenController 주석 추가
- [ ] UrlController 주석 추가
- [ ] UserController 주석 추가
