### ISSUE TITLE
[feat] : 클라우드를 GCP -> AWS로 이관한다

### ISSUE THREAD

**Issue by bbbang105** [onetime-with-members/backend#139]
### 📝 Description

- 클라우드를 GCP -> AWS로 이관한다

---

### 📝 Todo

- [x] 인스턴스, RDS 등 이관
- [x] GitHub Actions 스크립트 수정
- [x] 배포 서버 도메인 변경
