### ISSUE TITLE
[Refactor] : 멤버 등록 관련 리팩토링

### ISSUE THREAD

**Issue by bbbang105** [onetime-with-members/backend#15]
### 📝 Description

- 멤버 등록 로직과 관련한 리팩토링을 진행한다.

---

### 📝 Todo

- [x] 이름을 고유 값으로 지정
- [x] 멤버 로그인과 등록 로직을 분리
- [x] 멤버 초기 등록 API 구현
