### ISSUE TITLE
[fix, refactor] : QA 진행

### ISSUE THREAD

**Issue by bbbang105** [onetime-with-members/backend#18]
### 📝 Description

- QA 및 리팩토링을 진행한다.

---

### 📝 Todo

- [x] 이벤트 생성 시, DATE or DAY 구분 되지 않던 문제 해결
- [x] 날짜 & 요일 정렬되지 않던 문제 해결
- [x] 가능 인원 수가 같을 때 시간순으로 정렬이 안 되는 문제 해결
