### ISSUE TITLE
[feat] : 유저는 마이페이지에서 고정 스케줄을 상세 조회 & 수정 & 삭제할 수 있다

### ISSUE THREAD

**Issue by bbbang105** [onetime-with-members/backend#90]
### 📝 Description

- 유저는 마이페이지에서 고정 스케줄을 상세 조회 & 수정 & 삭제할 수 있다

---

### 📝 Todo

- [x] 고정 스케줄 상세 조회 API 구현
- [x] 고정 스케줄 수정 API 구현
- [x] 고정 스케줄 삭제 API 구현
